---
- name: Register an account.
  hosts: all
  gather_facts: no
  become: yes

  vars_files:
    - accounts.yml

  tasks:
    - name: Create a user account.
      ansible.builtin.user:
        user: "{{ item['name'] }}"
        password: "{{ item['password'] | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
      loop:
        "{{ accounts }}"