---
- name: Install Nginx
  hosts: marutamachi
  become: true
  tasks:
    - name: Ensure apt cache is up-to-date
      apt:
        update_cache: yes
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes