---
- name: Install Webmin
  hosts: all
  gather_facts: no
  become: yes
  vars_files: # tasks内には書けない
    - parameter.yml

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes # apt update相当
      loop: "{{ packages }}"

    - name: Add Webmin GPG key
      ansible.builtin.apt_key:
        url: http://www.webmin.com/jcameron-key.asc
        state: present

    - name: Add Webmin repository
      ansible.builtin.apt_repository:
        repo: deb http://download.webmin.com/download/repository sarge contrib
        filename: webmin
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Webmin
      ansible.builtin.apt:
        name: webmin
        state: present
