---
- name: How to use the community.general.read_csv module.
  hosts: all

  tasks:
    - name: Import the CSV file.
      community.general.read_csv:
        path: ./accounts.csv
      register: csv_values
      delegate_to: localhost
    - name: Display the loaded content.
      ansible.builtin.debug:
        var: csv_values
    - name: Display the loaded contents individually.
      ansible.builtin.debug:
        msg: "{{ item['name'] }} -> {{ item['password'] }}"
      loop:
        "{{ csv_values['list'] }}"
    - name: register user
      ansible.builtin.user: #https://zenn.dev/y_mrok/books/ansible-no-module-no-tsukaikata/viewer/ansible_builtin_user
        name: "{{ item['name'] }}"
        password: "{{ item['password'] }}"
      loop: "{{ csv_values['list'] }}"
      become: yes