---
- name: Register a repository for Webmin.
  ansible.builtin.blockinfile:
    path: "/etc/yum.repos.d/webmin.repo"
    create: yes
    block: |
      [webmin]
      name=Webmin Repository
      baseurl=http://download.webmin.com/download/yum/
      gpgcheck=1
      enabled=1
      gpgkey=http://www.webmin.com/jcameron-key.asc
    state: present
- name: Install the perl-Net-SSLeay module.
  ansible.builtin.dnf:
    name: perl-Net-SSLeay
    state: present
- name: Install the Webmin module.
  ansible.builtin.dnf:
    name: webmin
    state: present