---
 all:
   children:
     web:
       hosts:
         takeyamachi:
         oshikoji:
     mail:
       hosts:
         nijyo:
         ebisugawa:
     database:
       hosts:
         oshikoji:
         oike: