---
- name: Identify the OS and install Apache.
  hosts: all
  become: yes

  tasks:
    - name: RedHat system
      ansible.builtin.include_role:
        name: redhat
      when:
        - inventory_hostname in groups['web']
        - ansible_facts['os_family'] == "RedHat"
    - name: Debian system
      ansible.builtin.include_role:
        name: debian
      when:
        - inventory_hostname in groups['web']
        - ansible_facts['os_family'] == "Debian"